Team-QSS/KonoPuro-Unity

.idea/.idea.KonoPuro-Unity/.idea/indexLayout.xml
.idea/.idea.KonoPuro-Unity/.idea/projectSettingsUpdater.xml
Assets/NuGetForUnity.4.0.2.unitypackage.meta
Assets/SketchfabForUnity-v1.2.1.unitypackage.meta
Assets/_root/Script/Network/API.cs
Assets/_root/Script/Network/API.cs.meta
Assets/_root/Script/Network/Networking.cs
Assets/_root/Script/Network/Schemas.cs
Assets/_root/Script/Network/Schemas.cs.meta
Assets/_root/Script/Utils/EncryptedPlayerPrefs.cs
Assets/_root/Script/Utils/EncryptedPlayerPrefs.cs.meta

Network & API Setup

---

Assets/Curve.cs
Assets/_root/Script/Network/API.cs

ㄻㄴㄻ냐ㅕㄱ대거ㅣㅁ넝리ㅓㅌㅊ패ㅑ디ㅏㅈ귑;ㅕ잳ㄹ;ㅁ닝로;머ㅏ이럼ㄴ,ㅡㅊ
close #13

🔀 :: #13 배그하기

---

Assets/_root/Script/Main/Deck/DeckEditMenu.cs
Assets/_root/Script/Main/PlaceableObject.cs

🔀메인화면에서 자꾸 에딧창이 뜨는 버그 해결

---

Assets/_root/Prefabs/Ui/Progress Detail Element.prefab
Assets/_root/Script/Ingame/IngameUi.cs
Assets/_root/Script/Ingame/ProgressDetailElementUi.cs
Assets/_root/Script/Ingame/ProgressDetailUi.cs

Prograss update animation

---

Assets/Scenes/MainScene.unity
Assets/_root/Script/Ingame/IngameCardInfoUi.cs
Assets/_root/Script/Main/Deck/DeckCardFilterMenu.cs
Assets/_root/Script/Main/Deck/DeckEditMenu.cs

close #42
덱 편성 시 필터링 & 검색 기능 추가
+ 기타 버그(인게임 학생 카드 정보 표시 등) 수정

🔀 :: #42 Add Deck Edit Filter & Search

---

Assets/Scenes/CardGatchaMulti.unity
Assets/Scenes/CardGatchaSingle.unity
Assets/cardinrange/CardinrandomRange.cs
Assets/cardinrange/ExitGatcha.cs

close #48
가챠에서 모든 카드를 확인하기 전까진 화면을 나갈 수 없도록 수정

🔀:: #48 Edit Gacha Directing ExitButton

---

Assets/_root/Script/Title/AuthPanel.cs
Assets/_root/Script/Title/TitleManager.cs

🔀:: #58 회원가입을 성공적으로 한 이후 즉시 로그인 화면으로 이동하도록 변경

---

Assets/Scenes/MainScene.unity

카메라가 종이를 위에서 수직으로 내려보게 수정했습니다.
close #60

🔀:: #60 매칭 시 표시되는 종이의 내용이 더 잘 보이도록 카메라 위치 조정

---

Assets/Scenes/TitleScene.unity

🔀:: #69 오늘의 카드 위치 수정

---

Assets/Config.json
Assets/Config.json.meta
Assets/Recorded (1).anim
Assets/Recorded (1).anim.meta
Assets/Scenes/MainScene.unity
Assets/Timeline/Ingame/ConfigMenu.controller
Assets/Timeline/Ingame/ConfigMenu.controller.meta
Assets/_root/Prefabs/Ui/ConfigMenu.prefab
Assets/_root/Script/Config/Config.json
Assets/_root/Script/Config/Config.json.meta
Assets/_root/Script/Config/ConfigButton.cs
Assets/_root/Script/Config/ConfigInUI.cs
Assets/_root/Script/Config/Setting.cs
Assets/_root/Script/Config/UserInfoPanel.cs

🔀:: #62 Fix Anchor, Add anim

---

Assets/_root/Prefabs/Ui/ConfigMenu.prefab

설정 ui 내부에 잘못 박혀있던 deckcardfiltermenu 삭제

MainScene Error Fix

---

Assets/Resources/Audio/MAIN_BACKGROUND_SFX.wav.meta
Assets/_root/Script/Main/GachaUI.cs
Assets/_root/Script/Main/MainManager.cs

🔀:: #108 MainScene Audio

---

Assets/Scenes/MainScene.unity
Assets/UnityTechnologies/ParticlePack/Shared/Scripts/ShowPlayerGold.cs
Assets/_root/Script/Main/MainManager.cs
Assets/_root/Script/Main/PlaceableObject.cs

골드 오브젝트 클릭 시 -> 호버 시로 변경
호버 해제 시 다시 Gold로 바뀌게 변경
close #103

🔀:: #103 Show Golds On Hover

---

Assets/_root/Sprites/Character.png.meta
Assets/_root/Sprites/Filter.png.meta
Assets/_root/Sprites/Login.png.meta
Assets/_root/Sprites/Logout.png.meta
Assets/_root/Sprites/Return.png.meta
Assets/_root/Sprites/Setting.png.meta
Assets/_root/Sprites/ShutDown.png.meta
Assets/_root/Sprites/Skill.png.meta

버튼을 호버했을 때 스프라이트 모양이 미세하게 바뀌는 것 수정
close #101

🔀버튼 스프라이트 수정 완료

---

Assets/_root/Script/Title/TitleUi.cs

🔀 :: #113 골드 초기화 버그 수정

---

.gitignore
Assets/_root/Prefabs/Ui/ConfigMenu.prefab
Assets/_root/Script/Config/UserInfoPanel.cs
Assets/_root/Script/Network/API.cs
Assets/_root/Script/Network/Networking.cs
Assets/_root/Script/Network/Schemas.cs

🔀:: #98 Config buttons

---

Assets/Scenes/IngameScene.unity

카드 설명이 패널을 뚫는 오류 수정
fixed #118

🔀:: #118 fix: description text overflow

---

Assets/_root/Prefabs/Ui/DeckEditMenu.prefab

유니티 기본 스프라이트로 체크박스 변경
close #99

🔀:: #99 edit: checkbox accessibility

---

Assets/_root/Prefabs/Ui/ConfigMenu.prefab
Assets/_root/Script/Config/ConfigInUI.cs
Assets/_root/Script/Config/ConfigManager.cs

fps가 15단위로 바뀌지 않는 버그 수정
close #117

🔀:: #117 fix: fps limit

---

Assets/Scenes/MainScene.unity
Assets/_root/Script/Main/GachaDirecting.cs
Assets/_root/Script/Main/GachaUI.cs

🔀:: #102 Various boxes
